version: "3.2"
services:

    redis:
        image: "redis:alpine"
        command: redis-server --requirepass p@ssw0rd
        ports:
            - "6379:6379"
        volumes:
            - ./redis-volume/redis-data:/var/lib/redis
            - ./redis-volume/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_REPLICATION_MODE=master

    redisinsight:
        image: redislabs/redisinsight:latest
        ports:
            - "8001:8001"
        volumes:
            - ./redis-volume:/db 